### ISSUE TITLE
MQTT provider

### ISSUE THREAD

**Issue by szepeviktor** [stintel/vallumd#9]
Please consider mentioning https://www.cloudmqtt.com/
they are Amazon EC2 powered.

**Comment by stintel** [comment]
Sorry, but I don't want to advertise 3rd party services. It is up to the user to decide what he/she wants to use.

**Comment by szepeviktor** [comment]
OK. I've found it hard to set up an maintain a server.
They have a free plan for up to 10 connections.

**Comment by stintel** [comment]
The problem is, once a single 3rd party service is added, there is no reason not to add any other 3rd party service either. I rather simply not allow it, as it would increase maintenance burden (e.g. a service needs to be removed whenever the 3rd party behind it starts offering it). Next to that, it would also pollute the git history.
